#!/usr/bin/env python3
"""kernels/object_registry.py — the production-grade versioned object registry (POST-C1 spine).

Per the AXIOMS: the registry is the canonical truth; JSONL is the export; Postgres is the streaming
append layer. Versioned (object_id + input_hash), append + supersede, atomic writes, and a hash-chained
event ledger for tamper-detection.

Deterministic + stdlib-only. Streams (never bulk-loads) large registries.
"""
from __future__ import annotations
import hashlib, json, os, re, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REG_DIR = ROOT / "data" / "registries"
CONTRACTS = ROOT / "contracts" / "CANONICAL-DAG.yaml"

GENERATED = "GENERATED"
ENGINEERING_VALIDATED = "ENGINEERING_VALIDATED"
SPECIALIST_REVIEWED = "SPECIALIST_REVIEWED"

LAYERS = ["C1", "THEME", "ARGUMENT", "SYNTHESIS", "ESSAY", "EDUCATION"]


def _load_dag_prereqs() -> dict[str, list[str]]:
    """Compile {layer: [requires]} from CANONICAL-DAG.yaml (the single source of truth)."""
    if not CONTRACTS.exists():
        raise FileNotFoundError(f"canonical DAG manifest missing: {CONTRACTS}")
    deps = {}
    cur = None
    for line in CONTRACTS.read_text().splitlines():
        m = re.match(r"^  ([A-Z0-9]+):\s*$", line)
        if m:
            cur = m.group(1); deps.setdefault(cur, [])
            continue
        r = re.match(r"^\s+requires:\s*\[(.*?)\]", line)
        if r and cur:
            deps[cur] = [x.strip().strip('"').strip("'") for x in r.group(1).split(",") if x.strip()]
    return deps


PREREQS = _load_dag_prereqs()


def _path(layer: str) -> Path:
    return REG_DIR / f"{layer.lower()}-registry.jsonl"


def _load(layer: str) -> dict:
    p = _path(layer)
    reg = {"layer": layer.upper(), "objects": {}}
    if not p.exists():
        return reg
    for line in p.open(encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except Exception:
            continue
        oid = rec.get("object_id")
        if oid:
            reg["objects"].setdefault(oid, []).append(rec)
    return reg


def _atomic_write(path: Path, data: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(data); fh.flush(); os.fsync(fh.fileno())
        os.replace(tmp, str(path))
    finally:
        if os.path.exists(tmp):
            try: os.unlink(tmp)
            except OSError: pass


def _save(layer: str, reg: dict) -> None:
    REG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [json.dumps(v, ensure_ascii=False) for oid, vs in reg["objects"].items() for v in vs]
    _atomic_write(_path(layer), "\n".join(lines) + "\n")


def _ledger_key() -> bytes:
    """A local secret that anchors the event chain (red-team HIGH-6). Without it, an attacker
    cannot regenerate the chain. Stored 0600 outside the registries."""
    key_path = ROOT / "data" / ".ledger-key"
    if key_path.exists():
        return key_path.read_bytes()
    import secrets
    k = secrets.token_bytes(32)
    key_path.parent.mkdir(parents=True, exist_ok=True)
    key_path.write_bytes(k)
    try:
        os.chmod(key_path, 0o600)
    except Exception:
        pass
    return k


def append_event(event: dict, payload_digest: str = "") -> dict:
    """Append a keyed + payload-digested ObjectEvent (red-team HIGH-6).

    Each event hash includes a local secret (HMAC) so the chain can't be regenerated by a writer
    without the key, and a payload_digest so a registry record's content can be cross-checked."""
    import hmac
    p = REG_DIR / "object-events.jsonl"
    prev = "genesis"
    if p.exists():
        try:
            with p.open("rb") as fh:
                fh.seek(0, 2); size = fh.tell()
                if size:
                    fh.seek(max(0, size - 8192), 0)
                    for line in fh.read().decode("utf-8", errors="ignore").splitlines():
                        line = line.strip()
                        if line:
                            try: prev = json.loads(line).get("event_hash", prev)
                            except Exception: pass
        except Exception: pass
    canonical = json.dumps({"event": event, "payload_digest": payload_digest, "prev_hash": prev},
                           sort_keys=True, ensure_ascii=False)
    event_hash = hmac.new(_ledger_key(), canonical.encode(), hashlib.sha256).hexdigest()
    rec = {"ts": __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
           "prev_hash": prev, "event_hash": event_hash, "event": event,
           "payload_digest": payload_digest}
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec, ensure_ascii=False) + "\n"); fh.flush(); os.fsync(fh.fileno())
    return rec


def verify_event_chain() -> bool:
    import hmac
    p = REG_DIR / "object-events.jsonl"
    if not p.exists(): return True
    try:
        key = _ledger_key()
    except Exception:
        return False
    prev = "genesis"
    for line in p.read_text(encoding="utf-8").splitlines():
        if not line.strip(): continue
        rec = json.loads(line)
        canonical = json.dumps({"event": rec["event"], "payload_digest": rec.get("payload_digest", ""),
                                "prev_hash": rec.get("prev_hash", "")}, sort_keys=True, ensure_ascii=False)
        expect = hmac.new(key, canonical.encode(), hashlib.sha256).hexdigest()
        if rec.get("prev_hash") != prev or rec.get("event_hash") != expect:
            return False
        prev = rec["event_hash"]
    return True


def input_hash(payload) -> str:
    return hashlib.sha256(json.dumps(payload, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


def derivation_hash(parent_records: list[dict], prompt_fingerprint: str = "") -> str:
    """red-team HIGH-5: hash the INPUTS (parents + prompt), not the output payload.
    Anchors an object to what it was derived FROM, so a forged object can't relabel its source."""
    parts = []
    for p in parent_records:
        parts.append({"object_id": p.get("object_id"), "version": p.get("version"),
                      "input_hash": p.get("input_hash")})
    parts.append({"prompt": prompt_fingerprint})
    return hashlib.sha256(json.dumps(parts, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


# ── authority invariant (red-team CRITICAL-3): authority(projection) <= authority(parent) ──
# The epistemic ceiling ladder. A child can NEVER exceed the highest authority among its parents.
CEILING_RANK = {"MACHINE_PROPOSED": 0, "GENERATED": 0, "ENGINEERING_VALIDATED": 1,
                "SCHOLARLY_CORROBORATED": 2, "INDEPENDENT_REVIEWED": 3,
                "SPECIALIST_REVIEWED": 2, "ADJUDICATED": 4}


def parent_ceiling(input_refs: list[str]) -> int:
    """The highest epistemic ceiling among the referenced parent objects (across all layers)."""
    if not input_refs:
        return CEILING_RANK.get("MACHINE_PROPOSED", 0)
    best = 0
    for layer in LAYERS:
        for oid, vs in _load(layer)["objects"].items():
            if oid not in input_refs:
                continue
            for v in vs:
                if not v.get("superseded"):
                    rank = CEILING_RANK.get(v.get("status", "GENERATED"), 0)
                    if rank > best:
                        best = rank
    return best


def assert_authority_invariant(layer: str, status: str, input_refs: list[str]) -> None:
    """Enforce authority(projection) <= authority(parent). Raises ValueError on violation."""
    if layer == "C1":
        return  # the floor has no parents; its ceiling is what it is
    child = CEILING_RANK.get(status, 0)
    parent = parent_ceiling(input_refs)
    if child > parent:
        raise ValueError(
            f"authority invariant violated: {layer} {status} (rank {child}) > "
            f"max parent authority (rank {parent}); refs={input_refs}")


def versions(layer: str, object_id: str) -> list[dict]:
    return _load(layer)["objects"].get(object_id, [])


def current(layer: str, object_id: str) -> dict | None:
    for v in reversed(versions(layer, object_id)):
        if not v.get("superseded"):
            return v
    return None


def is_committed(layer: str, object_id: str, ih: str) -> bool:
    for v in versions(layer, object_id):
        if v.get("input_hash") == ih and not v.get("superseded") and v.get("status") in (GENERATED, ENGINEERING_VALIDATED, SPECIALIST_REVIEWED):
            return True
    return False


def commit(layer: str, object_id: str, ih: str, created_by: str, status: str = GENERATED,
           payload: dict | None = None, input_refs: list[str] | None = None) -> dict:
    # red-team MEDIUM-9: only a valid ladder status is accepted
    if status not in (GENERATED, ENGINEERING_VALIDATED, SPECIALIST_REVIEWED):
        raise ValueError(f"commit: invalid status {status!r} (not in the frozen ladder)")
    # red-team CRITICAL-3: enforce authority(projection) <= authority(parent)
    assert_authority_invariant(layer.upper(), status, input_refs or [])
    reg = _load(layer)
    vs = reg["objects"].get(object_id, [])
    prev = None
    for v in vs:
        if not v.get("superseded"):
            prev = v["version"]
    vnum = len(vs) + 1
    version = f"{layer.lower()}-{object_id}-v{vnum}"
    rec = {"layer": layer.upper(), "object_id": object_id, "version": version,
           "input_hash": ih, "input_refs": input_refs or [], "status": status,
           "created_by": created_by,
           "created_at": __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
           "supersedes": prev, "superseded": False, "payload": payload or {}, "review_events": []}
    vs.append(rec)
    reg["objects"][object_id] = vs
    _save(layer, reg)
    append_event({"type": "OBJECT_CREATED", "layer": layer, "object_id": object_id,
                  "input_hash": ih, "version": version, "created_by": created_by},
                 payload_digest=ih)
    return rec


def supersede(layer: str, object_id: str) -> list[str]:
    reg = _load(layer)
    changed = []
    for v in reg["objects"].get(object_id, []):
        if not v.get("superseded"):
            v["superseded"] = True
            v["superseded_at"] = __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat()
            changed.append(v["version"])
    _save(layer, reg)
    for v in changed:
        append_event({"type": "SUPERSEDED", "layer": layer, "object_id": object_id, "version": v})
    return changed


def eligible(layer: str) -> list[str]:
    """Deterministic eligibility (red-team CRITICAL-4): a layer is eligible for a C1 only when
    EVERY required parent (per CANONICAL-DAG) is committed with the correct object id.

    E.g. SYNTHESIS requires [ARGUMENT, THEME] → eligible only when both the ARGUMENT and the THEME
    for that C1 are committed. Returns the C1 ids whose required parents are all satisfied.
    """
    layer = layer.upper()
    if layer == "C1":
        return [oid for oid, vs in _load("C1")["objects"].items()
                for v in vs if not v.get("superseded")]
    requires = PREREQS.get(layer, [])
    c1s = [oid for oid, vs in _load("C1")["objects"].items()
           for v in vs if not v.get("superseded")]
    eligible_c1s = []
    for c1 in c1s:
        ok = True
        for parent in requires:
            # C1 is the floor (no suffix); other parents are <c1>__<parent> (e.g. __argument)
            parent_obj = c1 if parent == "C1" else f"{c1}__{parent.lower()}"
            cur = current(parent, parent_obj)
            if cur is None:
                ok = False
                break
        if ok:
            eligible_c1s.append(c1)
    return eligible_c1s


def summary() -> dict:
    out = {}
    for layer in LAYERS:
        reg = _load(layer)
        out[layer] = {"objects": len(reg["objects"]),
                      "versions": sum(len(v) for v in reg["objects"].values())}
    return out


if __name__ == "__main__":
    import sys
    print(json.dumps(summary(), indent=2))
